### ISSUE TITLE
Building of /etc/hosts includes wrong data

### ISSUE THREAD

**Issue by hut8** [holms/ansible-fqdn#10]
I've only been using this role when deploying to a single host. Recently that changed, and after I fixed #3 I noticed this in my /etc/hosts:

```
127.0.0.1       localhost
127.0.1.1       ibm704
...
1.2.3.4 ibm704.example.com ibm704
4.3.2.1 ibm704.example.com therac25
```

Yikes :astonished: My two hosts are ibm704.example.com and therac25.example.com. So the last line above should clearly be therac25.example.com instead of ibm704.example.com right? I just upgraded the role.

**Comment by holms** [comment]
Your pull request is the last in here: https://github.com/holms/ansible-fqdn/issues/3
You're welcome to fix this issue :)

**Comment by johnjelinek** [comment]
:+1:

**Comment by hut8** [comment]
My speculation on cause (disclaimer: I have no idea about the guts of Ansible):

https://github.com/holms/ansible-fqdn/blob/master/tasks/default.yml#L12
```yaml
- name: Build hosts file (backups will be made)
  lineinfile: dest=/etc/hosts line='{{ hostvars[item].ansible_default_ipv4.address }} {{ fqdn }} {{ hostvars[item].ansible_hostname }}' state=present backup=yes
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: groups['all']
```

Here, `{{ fqdn }}` remains constant throughout this loop -- it's the `fqdn` variable set in the playbook for a particular host (call that host "awesome_host.example.com"). Then this loops through each host, and pairs `hostvars[item].ansible_default_ipv4.address` with `fqdn`, which doesn't change in the body of the loop. A couple days ago I tried to figure out how you can get a role's variable *for a different host* in a play and couldn't find anything, then I gave up. That's my progress.

![it's something](http://img4.wikia.nocookie.net/__cb20130221021013/adventuretimewithfinnandjake/images/4/49/It's_something_(edited).png)
