### ISSUE TITLE
ansible-2.2.0.0 - Service module no longer works with async

### ISSUE THREAD

**Issue by manjitkumar** [holms/ansible-fqdn#26]
```yml
- name: restart hostname
  service: name=hostname state=restarted
  async: 45
  poll: 0
  when: ansible_distribution not in [ 'RedHat', 'CentOS' ]
```

refer - 
- https://github.com/ansible/ansible/issues/18965
- https://github.com/ansible/ansible/issues/18965#issuecomment-267080403
